language: go
sudo: false
env:
  - GO111MODULE=on
matrix:
  include:
    - os: linux
      go: 1.12.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
    - os: linux
      go: 1.11.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
    - os: osx
      go: 1.12.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
    - os: osx
      go: 1.11.x
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod
install:
  - go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - env GO111MODULE=on go build ./...
  - env GO111MODULE=on ./run_tests.sh
