sudo: required

language: go

services:
  - docker

env:
  - GOVERSION = 1.8
  - GOVERSION = 1.9

matrix:
  include:
    # build a library for iOS
    - os: osx # gomobile: target=ios requires the host machine to be running OS X.
      go: 1.9
      install:
        # setup the cocoapods master repo
        - gem uninstall cocoapods -a -x
        - gem install cocoapods
        - pod setup --verbose
      script:
        - gomobile bind -target ios -v github.com/decred/dcrd/mobile
      before_deploy:
        # render cocoapods spec based on a template (project root directory)
        -
        # ensure that we have a valid cocoapod spec
        - pod spec lint template.podspec 
      deploy:
        - pod trunk push DCRD.podspec --allow-warnings --verbose
    
    # build a library for Android
    - os:
      language: android
      before_install:
        # verify that the sdk and ndk are available
        - 
      script:
        - gomobile init -ndk $ANDROID_NDK # install android compiler toolchain
        - gomobile -target android -javapkg org.decred -v github.com/decred/dcrd/mobile
      before_deploy:
        # import key
        - gpg --import $MVN_KEY
      deploy:
        # sign & deploy to Maven Central
        - mvn gpg:sign-and-deploy-file -settings=mobile/mvn.settings -Durl=url -Drepository=repo -DpomFile=mobile/pom.xml -Dfile=dcrd.aar
  

install: true

script:
  - ./run_tests.sh $GOVERSION
