language: go
sudo: false
env:
  - GO111MODULE=on
matrix:
  include:
    - os: linux
      go: 1.12.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/go/pkg/mod
    - os: linux
      go: 1.11.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/go/pkg/mod
    - os: osx
      go: 1.12.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/go/pkg/mod
    - os: osx
      go: 1.11.x
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/go/pkg/mod
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
script:
  - env GO111MODULE=on go build ./...
  - env GO111MODULE=on ./run_tests.sh
